language: python
python: 3.5
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
install:
  - pip install tox
script:
  - tox
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libssl-dev swig
